add pipeline and necessary scripts
scilus/disco_challenge pull request #1
Opened 2021-07-20 18:20 UTC by Florence-G

2021-07-20 19:49 UTC, AntoineTheb requested changes
Juste un commentaire, sinon c'est parfait !

2021-07-20 19:49 UTC, AntoineTheb commented on code/DiSCo_connectivity_pipeline_1.0.1.sh
> +#!/bin/bash
Pas certain qu'on ait besoin de ce fichier ! On peut juste garder l'autre et enlever le "versioning"

2021-07-21 14:37 UTC, AntoineTheb requested changes
Après avoir testé, j'ai deux autres commentaires ultra-mineurs après c'est bon on merge !

2021-07-21 14:37 UTC, AntoineTheb commented on code/convert_npy2txt.py
> +#!/usr/bin/env python
Peux tu faire un `chmod +x" sur ce fichier ? Sinon ça plante à l'exécution !

2021-07-21 14:37 UTC, AntoineTheb commented on code/convert_txt2npy.py
> +#!/usr/bin/env python
Peux tu faire un `chmod +x" sur ce fichier ? Sinon ça plante à l'exécution !

2021-07-21 14:46 UTC, Florence-G commented on code/convert_npy2txt.py
> +#!/usr/bin/env python
Si je fais `chmod +x`, ça me dit que je n'ai pas de changement à pusher... as-tu une autre commande chmod?

2021-07-21 14:47 UTC, AntoineTheb commented on code/convert_npy2txt.py
> +#!/usr/bin/env python
J'ai mal donné les instructions désolé ! Essaie `chmod +x code/convert_npy2txt.py`

2021-07-21 14:52 UTC, Florence-G commented on code/convert_npy2txt.py
> +#!/usr/bin/env python
ah non mais ça c'est correct, c'est moi qui n'étais pas claire : si je fais git status apres les chmod, alors j'ai -­> rien à valider, la copie de travail est propre. Si je fais un commit, rien ne change je crois?

2021-07-21 14:53 UTC, Florence-G commented on code/convert_npy2txt.py
> +#!/usr/bin/env python
laisse laisse j'avais fait -x !!!!! désolé

2021-07-21 14:53 UTC, AntoineTheb commented on code/convert_npy2txt.py
> +#!/usr/bin/env python
Hmmmm tu devrais avoir des changements. Essaie ce qui est indiqué dans ce post: https://stackoverflow.com/a/40979016

2021-07-21 14:57 UTC, AntoineTheb approved these changes

2021-07-21 14:57 UTC, merged